name: Deploy Node.js Service

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-docker-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/node-docker-service:latest

      # - name: Deploy to remote server
      #   uses: appleboy/ssh-action@v0.1.10
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKER_USERNAME }}/node-docker-service:latest
      #       docker stop node-service || true
      #       docker rm node-service || true
      #       docker run -d --name node-service -p 3000:3000 --env-file /home/${{ secrets.SERVER_USER }}/.env ${{ secrets.DOCKER_USERNAME }}/node-docker-service:latest
